import type { FlowDefinition } from "../components/OnBoarding/types";

export const onboardingFlows: Record<string, FlowDefinition> = {
  commonSteps: {
    userType: "commonSteps",
    steps: {
      "1": {
        id: "1",
        type: "date",
        question: "¿Cuál es tu fecha de nacimiento?",
        saveTo: "birthday",
        nextStep: "2",
      },
      "2": {
        id: "2",
        type: "radio",
        question: "¿Con qué género te identificas?",
        options: [
          { value: "masculino", label: "Masculino" },
          { value: "femenino", label: "Femenino" },
          { value: "noAnswer", label: "Prefiero no decirlo" },
        ],
        saveTo: "genre",
        nextStep: "3",
      },
      "3": {
        id: "3",
        type: "text",
        question: "¿En qué país te encuentas actualmente?",
        saveTo: "country",
        nextStep: "4",
      },
      "4": {
        id: "4",
        type: "text",
        question: "¿En qué ciudad vives?",
        saveTo: "city",
        nextStep: "5",
      },
      "5": {
        id: "5",
        type: "text",
        question: "¿Cuál es tu número de contacto?",
        saveTo: "phone",
        nextStep: "6",
      },
      "6": {
        id: "6",
        type: "radio",
        question: "¿Como te gustaría involucrarte con Parent In?",
        options: [
          { value: "parental", label: "Soy madre, padre o persona gestante, quiero vivir la experiencia" },
          { value: "organization", label: "Soy organización, quiero saber más" },
          { value: "professional", label: "Soy profesional, quiero aplicar a la red" },
        ],
        saveTo: "userType",
        nextStep: "final"
      }
    }
  },
  parental: {
    userType: "parental",
    steps: {
      "1": {
        id: "1",
        type: "radio",
        question: "¿Qué opción te describe mejor?",
        options: [
          { value: "madre", label: "Madre" },
          { value: "padre", label: "Padre" },
          { value: "otro", label: "Otro (especificar)" },
        ],
        saveTo: "userDescription",
        nextStep: "2",
      },
      "2": {
        id: "2",
        type: "radio",
        question: "¿Qué tipo de familia te describe mejor?",
        options: [
          { value: "PADRE_MADRE", label: "Padre-Madre" },
          { value: "MADRE_MADRE", label: "Madre-Madre" },
          { value: "PADRE_PADRE", label: "Padre-Padre" },
          { value: "MADRE", label: "Madre" },
          { value: "PADRE", label: "Padre" },
          { value: "OTHER", label: "Otro (especificar)" },
        ],
        saveTo: "familyType",
        nextStep: "3",
      },
      "3": {
        id: "3",
        type: "radio",
        question: "¿Cuántos hijos/as tienes hoy?",
        options: [
          { value: "0", label: "0" },
          { value: "1", label: "1" },
          { value: "2", label: "2" },
          { value: "3", label: "3" },
          { value: "4 o más", label: "4 o más" },
        ],
        saveTo: "numberOfChildren",
        nextStep: "4",
      },
      "4": {
        id: "4",
        type: "radio",
        question: "Situación Laboral Actual",
        options: [
          { value: "trabajo full time", label: "Trabajo full time" },
          { value: "trabajo part time", label: "Trabajo part time" },
          { value: "estoy buscando trabajo", label: "Estoy buscando trabajo" },
          { value: "estoy en pausa laboral", label: "Estoy en pausa laboral" },
          { value: "otra", label: "Otro (especificar)" },
        ],
        saveTo: "currentEmploymentStatus",
        nextStep: "5",
      },
      "5": {
        id: "5",
        type: "radio",
        question: "Tipo de organización",
        options: [
          { value: "startup", label: "Startup(1-100)" },
          {
            value: "pyme",
            label: "Pequeña y Mediana Empresa (1-1000)",
          },
          {
            value: "corporación",
            label: "Corporación (+1000)",
          },
          { value: "ong/orgpublico", label: "ONG/Organismo Público" },
          { value: "trabajo por mi cuenta", label: "Trabajo por mi cuenta" },
          { value: "otra", label: "Otro (especificar)" },
        ],
        saveTo: "organizationType",
        nextStep: "6",
      },
      "6": {
        id: "6",
        type: "radio",
        question: "Rol o posición actual (o última ocupada)",
        options: [
          {
            value: "analista / especialista",
            label: "Analista / Especialista",
          },
          {
            value: "coordinación / supervisión",
            label: "Coordinación / Supervisión",
          },
          { value: "jefatura / liderazgo", label: "Jefatura / Liderazgo" },
          { value: "gerencia media", label: "Gerencia media" },
          { value: "alta dirección c-level", label: "Alta dirección C-Level" },
          { value: "trabajo por mi cuenta", label: "Trabajo por mi cuenta" },
          { value: "otra", label: "Otro (especificar)" },
        ],
        saveTo: "currentRole",
        nextStep: "7",
      },
      "7": {
        id: "7",
        type: "radio",
        question: "¿En qué etapa te encuentras?",
        options:[
          { value: "preLicencia", label: "Pre licencia: estoy esperando un bebé"},
          { value: "licencia", label: "Licencia: acabo de tener un bebé"},
          { value: "postLicencia", label: "Post licencia: Estoy volviendo al trabajo"},
        ],
        saveTo: "parentalStage",
        nextStep: "final",
      },
    },
  },
  preLicencia: {
    userType: "preLicencia",
    steps: {
      "1":{
        id: "1",
        type: "radio",
        question: "Felicitaciones!! ¿En qué trimestre te encuentras?",
        options: [
          { value: "TRIMESTER_1", label: "1er trimestre (1-12 semanas)" },
          { value: "TRIMESTER_2", label: "2do trimestre (13-26 semanas)" },
          { value: "TRIMESTER_3", label: "3er trimestre (27 semanas o mas)" },
        ],
        saveTo: "trimester",
        nextStep: "2",
      },
      "2":{
        id: "2",
        type: "date",
        question: "¿Para cúando esperas a tu bebé? Indica la fecha estimada para personalizar nuestras recomendaciones.",
        saveTo: "estimatedDueDate",
        nextStep: "3",
      },
      "3":{
        id: "3",
        type: "multiselect",
        question: "¿En qué necesitas apoyo?",
        options: [
          { value: "Diseñar y comunicar mi plan de traspaso de tareas (handover)", label: "Diseñar y comunicar mi plan de traspaso de tareas (handover)" },
          { value: "Construir una red de apoyo dentro y fuera del trabajo", label: "Construir una red de apoyo dentro y fuera del trabajo" },
          { value: "Conversar, acordar y redistribuir las tareas de cuidado en casa", label: "Conversar, acordar y redistribuir las tareas de cuidado en casa" },
          { value: "Definir plan de contacto durante la licencia", label: "Definir plan de contacto durante la licencia" },
          { value: "Establecer límites y cuidar mi bienestar", label: "Establecer límites y cuidar mi bienestar" },
          { value: "Prepararme emocionalmente y organizar lo práctico para esta etapa", label: "Prepararme emocionalmente y organizar lo práctico para esta etapa" },
          { value: "Recibir apoyo de la red de profesionales Parent In", label: "Recibir apoyo de la red de profesionales Parent In" },
          { value: "Aprender sobre parto, lactancia y cuidados", label: "Aprender sobre parto, lactancia y cuidados" },
          { value: "Conectar con el momento del nacimiento", label: "Conectar con el momento del nacimiento" },
          { value: "otra", label: "Otro (especificar)" },
        ],
        saveTo: "preLicenseSupportNeeds",
        nextStep: "final",
      },
    },
  },
  licencia: {
    userType: "licencia",
    steps: {
      "1":{
        id: "1",
        type: "date",
        question: "¡Felicitaciones! ¿Cuándo nació tu bebé? Indica la fecha para personalizar nuestras recomendaciones.",
        saveTo: "babyBirthDate",
        nextStep: "2",
      },
      "2":{
        id: "2",
        type: "radio",
        question: "¿Cuánto tiempo estarás de licencia? Comparte el tiempo estimado para personalizar nuestras recomendaciones.",
        options: [
          { value: "LESS_THAN_1_MONTH", label: "Menos de un mes" },
          { value: "ONE_TO_3_MONTHS", label: "1 a 3 meses" },
          { value: "THREE_TO_6_MONTHS", label: "3 a 6 meses" },
          { value: "MORE_THAN_6_MONTHS", label: "Más de 6 meses" },
          { value: "licenseDurationOther", label: "Otro (especificar)" },
        ],
        saveTo: "licenseDuration",
        nextStep: "3",
      },
      "3":{
        id: "3",
        type: "multiselect",
        question: "¿En qué necesitas apoyo?",
        options: [
          { value: "Cuidar mi salud mental y física", label: "Cuidar mi salud mental y física" },
          { value: "Procesar cambios emocionales, físicos y relacionales", label: "Procesar cambios emocionales, físicos y relacionales" },
          { value: "Aprender sobre puerperio, lactancia y cuidados", label: "Aprender sobre puerperio, lactancia y cuidados" },
          { value: "Recibir apoyo de la red de profesionales Parent In", label: "Recibir apoyo de la red de profesionales Parent In" },
          { value: "Fortalecer mi red de apoyo (pareja, familia, amistades)", label: "Fortalecer mi red de apoyo (pareja, familia, amistades)" },
          {value: "Construir acuerdos de corresponsabilidad en casa", label: "Construir acuerdos de corresponsabilidad en casa" },
          {value: "Establecer límites y pedir ayuda", label: "Establecer límites y pedir ayuda" },
          {value: "Ordenar mis días y armar rutinas sostenibles", label: "Ordenar mis días y armar rutinas sostenibles" },
          {value: "Pensar cómo sería mi vuelta al trabajo", label: "Pensar cómo sería mi vuelta al trabajo" },
          { value: "otra", label: "Otro (especificar)" },
        ],
        saveTo: "licenseSupportNeeds",
        nextStep: "final",
      }
    },
  },
  postLicencia: {
    userType: "postLicencia",
    steps: {
      "1":{
        id: "1",
        type: "date",
        question: "¿Cuándo regresas o regresaste al trabajo luego de tu licencia?",
        saveTo: "returnDate",
        nextStep: "2",
      },
      "2":{
        id: "2",
        type: "radio",
        question: "¿Cómo es tu vuelta al trabajo?",
        options: [
          { value: "FULL_TIME_PRESENTIAL", label: "Full-time Presencial" },
          { value: "FULL_TIME_HYBRID", label: "Full-time Hibrido" },
          { value: "FULL_TIME_REMOTE", label: "Full-time 100% Remoto" },
          { value: "PART_TIME_PRESENTIAL", label: "Part-time Presencial" },
          { value: "PART_TIME_HYBRID", label: "Part-time Hibrido" },
          { value: "PART_TIME_REMOTE", label: "Part-time 100% Remoto" },
          { value: "workModalityOther", label: "Otro (especificar)" },
        ],
        saveTo: "workModality",
        nextStep: "3",
      },
      "3":{
        id: "3",
        type: "multiselect",
        question: "¿En qué necesitas apoyo?",
        options: [
          { value: "Diseñar mi plan de vuelta al trabajo", label: "Diseñar mi plan de vuelta al trabajo" },
          { value: "Gestionar emociones y reconectar con mi propósito", label: "Gestionar emociones y reconectar con mi propósito" },
          { value: "Tener conversaciones difíciles (con líderes, equipo o familia)", label: "Tener conversaciones difíciles (con líderes, equipo o familia)" },
          { value: "Establecer límites y cuidar mi salud mental", label: "Establecer límites y cuidar mi salud mental" },
          { value: "Negociar acuerdos o nuevas formas de trabajo", label: "Negociar acuerdos o nuevas formas de trabajo" },
          { value: "Organizar tiempos, prioridades y responsabilidades", label: "Organizar tiempos, prioridades y responsabilidades" },
          { value: "Reencontrar el equilibrio entre trabajo y familia", label: "Reencontrar el equilibrio entre trabajo y familia" },
          {value: "Construir acuerdos de corresponsabilidad en casa", label: "Construir acuerdos de corresponsabilidad en casa" },
          {value: "Reconocer y procesar los cambios (internos y externos)", label: "Reconocer y procesar los cambios (internos y externos)" },
          {value: "Ordenar mis días y armar rutinas sostenibles", label: "Ordenar mis días y armar rutinas sostenibles" },
          {value: "Fortalecer mi red de apoyo y distribuir tareas de cuidado", label: "Fortalecer mi red de apoyo y distribuir tareas de cuidado" },
          {value: "Recibir apoyo de la red de profesionales Parent In", label: "Recibir apoyo de la red de profesionales Parent In" },
          {value: "Recibir apoyo en la lactancia", label: "Recibir apoyo en la lactancia" },
          { value: "otra", label: "Otro (especificar)" },
        ],
        saveTo: "postLicenseSupportNeeds",
        nextStep: "final",
      }
    }
  },
  organization: {
    userType: "organization",
    steps: {
        "1": {
          id: "1",
          type: "text",
          question: "Nombre de la organización",
          saveTo: "organizationName",
          nextStep: "2",
        },
        "2": {
          id: "2",
          type: "radio",
          question: "Industria",
          options: [
            { value: "tecnología", label: "Tecnología / Software / SaaS" },
            { value: "servProf", label: "Servicios Profesionales" },
            { value: "finanzas", label: "Finanzas / Fintech / Seguros" },
            { value: "salud", label: "Salud / Bienestar / Pharma" },
            { value: "educación", label: "Educación / Edtech" },
            { value: "comercio", label: "Comercio / Retail / eCommerce" },
            { value: "manufactura", label: "Manufactura / Producción / Industria" },
            { value: "ernergia", label: "Energía / Minería / Oil & Gas" },
            { value: "telecomunicaciones", label: "Telecomunicaciones / Medios" },
            { value: "publico", label: "Sector Público / ONG" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "organizationIndustry",
          nextStep: "3",
        },
        "3": {
          id: "3",
          type: "radio",
          question: "Tamaño",
          options: [
            { value: "startup", label: "Startup (1-100)" },
            { value: "pyme", label: "Pequeña y Mediana Empresa (1-1000)" },
            { value: "corporacion", label: "Corporación (+1000)" },
            { value: "ong/orgpublico", label: "ONG/Organismo Público" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "organizationSize",
          nextStep: "4",
        },
        "4": {
          id: "4",
          type: "text",
          question: "Rol dentro de la organización",
          saveTo: "organizationRole",
          nextStep: "5",
        },
        "5": {
          id: "5",
          type: "radio",
          question: "¿Distribución de género en la organización? (Incluye personas no binarias si las hay)",
          options: [
            { value: "MAYORIA_FEMENINO", label: "Mayoría Mujeres (60% o más)" },
            { value: "MAYORIA_MASCULINO", label: "Mayoría Varones (60% o más)" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "genderDistribution",
          nextStep: "6",
        },
        "6": {
          id: "6",
          type: "radio",
          question: "¿Qué porcentaje aproximado de mujeres en la organización son madres?",
          options: [
            { value: "LESS_THAN_20", label: "0-20" },
            { value: "BETWEEN_21_AND_40", label: "21-40" },
            { value: "BETWEEN_41_AND_60", label: "41-60" },
            { value: "MORE_THAN_60", label: "Más de 60%" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "percentageMothers",
          nextStep: "7",
        },
        "7": {
          id: "7",
          type: "radio",
          question: "¿Qué porcentaje aproximado de varones en la organización son padres?",
          options: [
            { value: "LESS_THAN_20", label: "0-20" },
            { value: "BETWEEN_21_AND_40", label: "21-40" },
            { value: "BETWEEN_41_AND_60", label: "41-60" },
            { value: "MORE_THAN_60", label: "Más de 60%" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "percentageFathers",
          nextStep: "8",
        },
        "8": {
          id: "8",
          type: "radio",
          question: "¿Cúantos días de licencia toman efectivamente las mujeres/madres aproximadamente?",
          options: [
            { value: "legal", label: "Solo licencia legal" },
            { value: "legalExtendRemun", label: "Legal + extensión remunerada" },
            { value: "legalExtendNORemun", label: "Legal + extensión no remunerada" },
            { value: "legalExtendMixta", label: "Legal + extensión mixta (parte remunerada y parte no)" },
            { value: "masDeTresMeses", label: "Mas de tres meses adicionales (cualquier modalidad)" },
            { value: "variabls", label: "Varía según el caso" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "maternityLeaveDays",
          nextStep: "9",
        },
        "9": {
          id: "9",
          type: "radio",
          question: "¿Cúantos días de licencia toman efectivamente los varones/padres aproximadamente?",
          options: [
            { value: "no", label: "No la toman" },
            { value: "BETWEEN_1_AND_7_DAYS", label: "1-7 días" },
            { value: "BETWEEN_1_AND_3_WEEKS", label: "1-3 semanas" },
            { value: "BETWEEN_1_AND_2_MONTHS", label: "1-2 meses" },
            { value: "MORE_THAN_2_MONTHS", label: "Más de 2 meses" },
            { value: "variabls", label: "Varía según el caso" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "paternityLeaveDays",
          nextStep: "10",
        },
        "10": {
          id: "10",
          type: "number",
          question: "¿Que tán flexible es tu organización para trabajar por objetivos, adaptar horarios y formas de trabajo? Escala del 1 al 5, donde 1 es muy insatisfactorio y 5 es muy satisfactorio.",
          saveTo: "flexibilityScore",
          nextStep: "11",
          validation: {
            minLength: 1,
            maxLength: 5,
            errorMessage: "Por favor ingresa un número entre 1 y 5",
          },
        },
        "11": {
          id: "11",
          type: "number",
          question: "¿Cómo evaluas el equilibrio entre trabajo y cuidado que hay dentro de la organizacion? Escala del 1 al 5, donde 1 es muy insatisfactorio y 5 es muy satisfactorio.",
          saveTo: "workLifeBalanceScore",
          nextStep: "12",
          validation: {
            minLength: 1,
            maxLength: 5,
            errorMessage: "Por favor ingresa un número entre 1 y 5",
          },
        },
        "12": {
          id: "12",
          type: "number",
          question: "¿Cómo evaluarías el nivel de apoyo emocional percibido en la organizacion? Escala del 1 al 5, donde 1 es muy insatisfactorio y 5 es muy satisfactorio.",
          saveTo: "emotionalSupportScore",
          nextStep: "13",
          validation: {
            minLength: 1,
            maxLength: 5,
            errorMessage: "Por favor ingresa un número entre 1 y 5",
          },
        },
        "13": {
          id: "13",
          type: "multiselect",
          question: "¿Qué tipo de iniciativas existen dentro de tu organización?",
          options: [
            { value: "parentalLeave", label: "Licencias parentales" },
            { value: "licenseExtension", label: "Extensiones de licencia" },
            { value: "flexibleWork", label: "Flexibilidad laboral" },
            { value: "parentalTransition", label: "Transición parental y vuelta al trabajo gradual" },
            { value: "spacesSupportForBreastfeeding", label: "Espacios y apoyo a la lactancia" },
            { value: "careBenefits", label: "Beneficios de cuidado (guardaria, reintegros, etc." },
            { value: "emotionalSupport", label: "Salud mental y bienestar" },
            { value: "coachingParental", label: "Coaching parental / laboral" },
            { value: "workshops", label: "Talleres (cultura, liderazgo, corresponsabilidad, etc.)" },
            { value: "organizationalPrioritizationTools", label: "Herramientas de organización y prioridades" },
            { value: "communityOfCarers", label: "Comunidad de personas que cuidan" },
            { value: "well-beingSurveys", label: "Encuestas de bienestar (pulse)" },
            { value: "metricsAndUsageDashboard", label: "Métricas y dashboard de uso" },
            { value: "networkOfProfessionals", label: "Red de profesionales (puericultora, psicóloga perinaltal, etc.)" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "currentInitiatives",
          nextStep: "14",
        },
        "14": {
          id: "14",
          type: "multiselect",
          question: "¿Qué tipo de iniciativas buscan incorporar/fortalecer dentro de tu organización?",
          options: [
            { value: "parentalLeave", label: "Licencias parentales" },
            { value: "licenseExtension", label: "Extensiones de licencia" },
            { value: "flexibleWork", label: "Flexibilidad laboral" },
            { value: "parentalTransition", label: "Transición parental y vuelta al trabajo gradual" },
            { value: "spacesSupportForBreastfeeding", label: "Espacios y apoyo a la lactancia" },
            { value: "careBenefits", label: "Beneficios de cuidado (guardaria, reintegros, etc." },
            { value: "emotionalSupport", label: "Salud mental y bienestar" },
            { value: "coachingParental", label: "Coaching parental / laboral" },
            { value: "workshops", label: "Talleres (cultura, liderazgo, corresponsabilidad, etc.)" },
            { value: "organizationalPrioritizationTools", label: "Herramientas de organización y prioridades" },
            { value: "communityOfCarers", label: "Comunidad de personas que cuidan" },
            { value: "well-beingSurveys", label: "Encuestas de bienestar (pulse)" },
            { value: "metricsAndUsageDashboard", label: "Métricas y dashboard de uso" },
            { value: "networkOfProfessionals", label: "Red de profesionales (puericultora, psicóloga perinaltal, etc.)" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "desiredInitiatives",
          nextStep: "15",
        },
        "15": {
          id: "15",
          type: "radio",
          question: "¿Cuál de estas afirmaciones describe mejor la situación actual de tu organización?",
          options: [
            { value: "individualShares", label: "Tenemos acciones sueltas sin procesos ni cultura que las sostenga" },
            { value: "definedPolicies", label: "Tenemos políticas definidas pero con implementacion desigual" },
            { value: "policiesAndProcesses", label: "Tenemos polícas + procesos + culturas que las soistienen" },
            { value: "weMeasureImpact", label: "Además medimos impacto, mejoramos y el liderazgo modela estos comportamientos" },
          ],
          saveTo: "organizationalMaturity",
          nextStep: "16",
        },
        "16": {
          id: "16",
          type: "multiselect",
          question: "¿Cúales son los desafios prioritarios para tu organización al cuidado-trabajo? Selecciona hasta 5 opciones",
          options: [
            { value: "talentTurnover", label: "Rotación de talento" },
            { value: "recruitmentAndTrainingCosts", label: "Costos de contratación y entrenamiento" },
            { value: "absenteeism", label: "Ausentismo" },
            { value: "productivity", label: "Productividad" },
            { value: "burnout", label: "Burnout" },
            { value: "operationalCapacity", label: "Capacidad operativa" },
            { value: "retentionPostLeave", label: "Retorno / Retención post-licencia" },
            { value: "leadership", label: "Liderazgo" },
            { value: "genderEquity", label: "Equidad de género" },
            { value: "benefitsUsage", label: "Uso de beneficios / licencias" },
            { value: "engagementClima", label: "Engagement / clima" },
            { value: "flexibilityWorkLifeBalance", label: "Flexibilidad y equilibrio trabajo-cuidado" },
            { value: "mentalHealthSupport", label: "Salud mental y apoyo percibido" },
            { value: "otra", label: "Otro (especificar)" },
          ],
          saveTo: "organizationalChallenges",
          nextStep: "final",
        }
      },
  },
  professional: {
    userType: "professional",
    steps: {
      "1": {
        id: "1",
        type: "text",
        question: "LinkedIn o CV en la nube [Compartí tu informacion apra conocer tu profesión y formación]",
        saveTo: "linkedinOrCV",
        nextStep: "2",
      },
      "2": {
        id: "2",
        type: "multiselect",
        question: "¿En qué áreas te espcializas? [Selecciona todas las que apliquen]",
        options: [
          { value: "psychology", label: "Psicología" },
          { value: "perinatalPsychology", label: "Psicología perinaltal" },
          { value: "psychiatry", label: "Psiquiatría" },
          { value: "counseling", label: "Counselling" },
          { value: "couplesTherapy", label: "Terapia de pareja" },
          { value: "familyTherapy", label: "Terapia familiar" },
          { value: "personalCoaching", label: "Coaching personal" },
          { value: "parentalCoaching", label: "Coaching parental" },
          { value: "ontologicalCoaching", label: "Coaching ontológico" },
          { value: "laboralCoaching", label: "Coaching laboral" },
          { value: "careerCoaching", label: "Coaching de carrera" },
          { value: "executiveCoaching", label: "Coaching ejecutivo" },
          { value: "leadershipCoaching", label: "Coaching en liderazgo" },
          { value: "neuroscienceAndParenting", label: "Neurociencias y parentalidad" },
          { value: "doula", label: "Doula" },
          { value: "midwifery", label: "Partería" },
          { value: "puericulture", label: "Puericultura" },
          { value: "lactation", label: "Lactancia" },
          { value: "childcare", label: "Crianza" },
          { value: "infantSleep", label: "Sueño infantil" },
          { value: "adoptionSupport", label: "Acompañamiento en adopción" },
          { value: "fertilitySupport", label: "Acompañamiento en fertilidad y reproducción asistida" },
          { value: "psychopedagogy", label: "Psicopedagogía" },
          { value: "occupationalTherapy", label: "Terapia ocupacional" },
          { value: "neonatology", label: "Neonatología" },
          { value: "generalMedicine", label: "Medicina general" },
          { value: "gynecology", label: "Ginecología" },
          { value: "sexualAndReproductiveHealth", label: "Salud sexual y reproductiva" },
          { value: "obstetrics", label: "Obstetricia" },
          { value: "pediatrics", label: "Pediatría" },
          { value: "nutrition", label: "Nutrición" },
          { value: "physicalTherapy", label: "Fisioterapia" },
          { value: "kinesiology", label: "Kinesiología" },
          { value: "postpartumRehabilitation", label: "Rehabilitación física postparto" },
          { value: "sports", label: "Deporte" },
          { value: "meditationTechniques", label: "Técnicas de meditación" },
          { value: "genderPerspectiveConsulting", label: "Consultoría con perspectiva de género" },
          { value: "organizationalCulture", label: "Cultura organizacional" },
          { value: "deiAndGender", label: "DEI y género" },
          { value: "publicPolicies", label: "Políticas públicas" },
          { value: "workshopsAndFacilitation", label: "Facilitación y diseño de talleres" },
          { value: "communicationAndContentCreation", label: "Comunicación y creación de contenido" },
          { value: "productDesign", label: "Diseño de producto (UX)" },
          { value: "technologyAndData", label: "Tecnología, IA, Datos" },
          { value: "other", label: "Otro (especificar)" },
        ],
        saveTo: "areasOfSpecialization",
        nextStep: "3",
      },
      "3": {
        id: "3",
        type: "text",
        question: "Precio estmimado (USD) por sesión o unidad de servicio. Este dato nos ayuda a ajustar tarifas y paquetes en función de la diversidad de perfiles.",
        saveTo: "estimatedPricePerSession",
        nextStep: "4",
      },
      "4": {
        id: "4",
        type: "text",
        question: "¿Qué te motiva a colaborar con Parent In? Contanos qué te interesa de este proyecto.",
        saveTo: "motivation",
        nextStep: "final",
      }

    }
  },

};
